package com.yinqiao.af.model;

public class Announcement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CYZG_KSXZ.MSGID
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    private String msgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CYZG_KSXZ.TITLE
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CYZG_KSXZ.ADDTIME
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    private String addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CYZG_KSXZ.MSGTYPEID
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    private String msgtypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CYZG_KSXZ.REMARK
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CYZG_KSXZ.ISPUB
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    private String ispub;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CYZG_KSXZ.FLAG
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    private String flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CYZG_KSXZ.ISNEW
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    private String isnew;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CYZG_KSXZ.CONTENT
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CYZG_KSXZ.MSGID
     *
     * @return the value of CYZG_KSXZ.MSGID
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    public String getMsgid() {
        return msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CYZG_KSXZ.MSGID
     *
     * @param msgid the value for CYZG_KSXZ.MSGID
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    public void setMsgid(String msgid) {
        this.msgid = msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CYZG_KSXZ.TITLE
     *
     * @return the value of CYZG_KSXZ.TITLE
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CYZG_KSXZ.TITLE
     *
     * @param title the value for CYZG_KSXZ.TITLE
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CYZG_KSXZ.ADDTIME
     *
     * @return the value of CYZG_KSXZ.ADDTIME
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    public String getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CYZG_KSXZ.ADDTIME
     *
     * @param addtime the value for CYZG_KSXZ.ADDTIME
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    public void setAddtime(String addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CYZG_KSXZ.MSGTYPEID
     *
     * @return the value of CYZG_KSXZ.MSGTYPEID
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    public String getMsgtypeid() {
        return msgtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CYZG_KSXZ.MSGTYPEID
     *
     * @param msgtypeid the value for CYZG_KSXZ.MSGTYPEID
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    public void setMsgtypeid(String msgtypeid) {
        this.msgtypeid = msgtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CYZG_KSXZ.REMARK
     *
     * @return the value of CYZG_KSXZ.REMARK
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CYZG_KSXZ.REMARK
     *
     * @param remark the value for CYZG_KSXZ.REMARK
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CYZG_KSXZ.ISPUB
     *
     * @return the value of CYZG_KSXZ.ISPUB
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    public String getIspub() {
        return ispub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CYZG_KSXZ.ISPUB
     *
     * @param ispub the value for CYZG_KSXZ.ISPUB
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    public void setIspub(String ispub) {
        this.ispub = ispub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CYZG_KSXZ.FLAG
     *
     * @return the value of CYZG_KSXZ.FLAG
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CYZG_KSXZ.FLAG
     *
     * @param flag the value for CYZG_KSXZ.FLAG
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CYZG_KSXZ.ISNEW
     *
     * @return the value of CYZG_KSXZ.ISNEW
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    public String getIsnew() {
        return isnew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CYZG_KSXZ.ISNEW
     *
     * @param isnew the value for CYZG_KSXZ.ISNEW
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    public void setIsnew(String isnew) {
        this.isnew = isnew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CYZG_KSXZ.CONTENT
     *
     * @return the value of CYZG_KSXZ.CONTENT
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CYZG_KSXZ.CONTENT
     *
     * @param content the value for CYZG_KSXZ.CONTENT
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }
}