package com.yinqiao.af.model;

public class Enroll {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.BMKID
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String bmkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.IDTYPE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String idtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.IDCARD
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.KSNAME
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String ksname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.NETPSWORD
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String netpsword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.MOBICODE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String mobicode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.EMAIL
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.BMTIME
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String bmtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.ZKZH
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String zkzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.SEX
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.NATION
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.BIRTHDAY
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.HEIGHTXL
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String heightxl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.HEIGHTXLOVERTIME
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String heightxlovertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.HEIGHTZY
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String heightzy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.HEIGHTXLSCHOOL
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String heightxlschool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.ADDR
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.ADDRESSDETAIL
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String addressdetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.PHONECODE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String phonecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.POSTCODE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String postcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.BANKINFO
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String bankinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.BANKCITY
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String bankcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.BRANCH
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String branch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.ISCONFIRM
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String isconfirm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.CHECKED
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String checked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.CHECKMAN
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String checkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.CHECKTIME
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String checktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.FEEMAN
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String feeman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.FEETIME
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String feetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.CLFEES
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String clfees;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.KSFEES
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String ksfees;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.MONEYS
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String moneys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.FEESSTATUS
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String feesstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.KSDQID
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private Long ksdqid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.KSTIME
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String kstime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.KSSOURCE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String kssource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.KSADDR
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String ksaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.KCBH
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String kcbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.PCCODE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String pccode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.KCH
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String kch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.KSDATE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String ksdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.KSTIMESID
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String kstimesid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.KSTIMES
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String kstimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.KSPC
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String kspc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.PCID
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String pcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.PXFEES
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String pxfees;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.ISPX
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private Long ispx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.PXFEEMAN
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String pxfeeman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.PXFEEDATE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String pxfeedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.PXDATE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String pxdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.ISPRINTPASS
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String isprintpass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.PSDATE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String psdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.PSDATE2
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String psdate2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.STATUS
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private Long status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.KSCOUNT
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private Long kscount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.ISZCKS
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String iszcks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_BMK.KSSTATUS
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    private String ksstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.BMKID
     *
     * @return the value of FJB_BMK.BMKID
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getBmkid() {
        return bmkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.BMKID
     *
     * @param bmkid the value for FJB_BMK.BMKID
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setBmkid(String bmkid) {
        this.bmkid = bmkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.IDTYPE
     *
     * @return the value of FJB_BMK.IDTYPE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getIdtype() {
        return idtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.IDTYPE
     *
     * @param idtype the value for FJB_BMK.IDTYPE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setIdtype(String idtype) {
        this.idtype = idtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.IDCARD
     *
     * @return the value of FJB_BMK.IDCARD
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.IDCARD
     *
     * @param idcard the value for FJB_BMK.IDCARD
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.KSNAME
     *
     * @return the value of FJB_BMK.KSNAME
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getKsname() {
        return ksname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.KSNAME
     *
     * @param ksname the value for FJB_BMK.KSNAME
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setKsname(String ksname) {
        this.ksname = ksname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.NETPSWORD
     *
     * @return the value of FJB_BMK.NETPSWORD
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getNetpsword() {
        return netpsword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.NETPSWORD
     *
     * @param netpsword the value for FJB_BMK.NETPSWORD
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setNetpsword(String netpsword) {
        this.netpsword = netpsword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.MOBICODE
     *
     * @return the value of FJB_BMK.MOBICODE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getMobicode() {
        return mobicode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.MOBICODE
     *
     * @param mobicode the value for FJB_BMK.MOBICODE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setMobicode(String mobicode) {
        this.mobicode = mobicode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.EMAIL
     *
     * @return the value of FJB_BMK.EMAIL
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.EMAIL
     *
     * @param email the value for FJB_BMK.EMAIL
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.BMTIME
     *
     * @return the value of FJB_BMK.BMTIME
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getBmtime() {
        return bmtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.BMTIME
     *
     * @param bmtime the value for FJB_BMK.BMTIME
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setBmtime(String bmtime) {
        this.bmtime = bmtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.ZKZH
     *
     * @return the value of FJB_BMK.ZKZH
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getZkzh() {
        return zkzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.ZKZH
     *
     * @param zkzh the value for FJB_BMK.ZKZH
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setZkzh(String zkzh) {
        this.zkzh = zkzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.SEX
     *
     * @return the value of FJB_BMK.SEX
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.SEX
     *
     * @param sex the value for FJB_BMK.SEX
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.NATION
     *
     * @return the value of FJB_BMK.NATION
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.NATION
     *
     * @param nation the value for FJB_BMK.NATION
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setNation(String nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.BIRTHDAY
     *
     * @return the value of FJB_BMK.BIRTHDAY
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.BIRTHDAY
     *
     * @param birthday the value for FJB_BMK.BIRTHDAY
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.HEIGHTXL
     *
     * @return the value of FJB_BMK.HEIGHTXL
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getHeightxl() {
        return heightxl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.HEIGHTXL
     *
     * @param heightxl the value for FJB_BMK.HEIGHTXL
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setHeightxl(String heightxl) {
        this.heightxl = heightxl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.HEIGHTXLOVERTIME
     *
     * @return the value of FJB_BMK.HEIGHTXLOVERTIME
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getHeightxlovertime() {
        return heightxlovertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.HEIGHTXLOVERTIME
     *
     * @param heightxlovertime the value for FJB_BMK.HEIGHTXLOVERTIME
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setHeightxlovertime(String heightxlovertime) {
        this.heightxlovertime = heightxlovertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.HEIGHTZY
     *
     * @return the value of FJB_BMK.HEIGHTZY
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getHeightzy() {
        return heightzy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.HEIGHTZY
     *
     * @param heightzy the value for FJB_BMK.HEIGHTZY
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setHeightzy(String heightzy) {
        this.heightzy = heightzy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.HEIGHTXLSCHOOL
     *
     * @return the value of FJB_BMK.HEIGHTXLSCHOOL
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getHeightxlschool() {
        return heightxlschool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.HEIGHTXLSCHOOL
     *
     * @param heightxlschool the value for FJB_BMK.HEIGHTXLSCHOOL
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setHeightxlschool(String heightxlschool) {
        this.heightxlschool = heightxlschool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.ADDR
     *
     * @return the value of FJB_BMK.ADDR
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.ADDR
     *
     * @param addr the value for FJB_BMK.ADDR
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.ADDRESSDETAIL
     *
     * @return the value of FJB_BMK.ADDRESSDETAIL
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getAddressdetail() {
        return addressdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.ADDRESSDETAIL
     *
     * @param addressdetail the value for FJB_BMK.ADDRESSDETAIL
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setAddressdetail(String addressdetail) {
        this.addressdetail = addressdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.PHONECODE
     *
     * @return the value of FJB_BMK.PHONECODE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getPhonecode() {
        return phonecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.PHONECODE
     *
     * @param phonecode the value for FJB_BMK.PHONECODE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setPhonecode(String phonecode) {
        this.phonecode = phonecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.POSTCODE
     *
     * @return the value of FJB_BMK.POSTCODE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.POSTCODE
     *
     * @param postcode the value for FJB_BMK.POSTCODE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.BANKINFO
     *
     * @return the value of FJB_BMK.BANKINFO
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getBankinfo() {
        return bankinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.BANKINFO
     *
     * @param bankinfo the value for FJB_BMK.BANKINFO
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setBankinfo(String bankinfo) {
        this.bankinfo = bankinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.BANKCITY
     *
     * @return the value of FJB_BMK.BANKCITY
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getBankcity() {
        return bankcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.BANKCITY
     *
     * @param bankcity the value for FJB_BMK.BANKCITY
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setBankcity(String bankcity) {
        this.bankcity = bankcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.BRANCH
     *
     * @return the value of FJB_BMK.BRANCH
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getBranch() {
        return branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.BRANCH
     *
     * @param branch the value for FJB_BMK.BRANCH
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setBranch(String branch) {
        this.branch = branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.ISCONFIRM
     *
     * @return the value of FJB_BMK.ISCONFIRM
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getIsconfirm() {
        return isconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.ISCONFIRM
     *
     * @param isconfirm the value for FJB_BMK.ISCONFIRM
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setIsconfirm(String isconfirm) {
        this.isconfirm = isconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.CHECKED
     *
     * @return the value of FJB_BMK.CHECKED
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getChecked() {
        return checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.CHECKED
     *
     * @param checked the value for FJB_BMK.CHECKED
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setChecked(String checked) {
        this.checked = checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.CHECKMAN
     *
     * @return the value of FJB_BMK.CHECKMAN
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getCheckman() {
        return checkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.CHECKMAN
     *
     * @param checkman the value for FJB_BMK.CHECKMAN
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setCheckman(String checkman) {
        this.checkman = checkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.CHECKTIME
     *
     * @return the value of FJB_BMK.CHECKTIME
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.CHECKTIME
     *
     * @param checktime the value for FJB_BMK.CHECKTIME
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setChecktime(String checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.FEEMAN
     *
     * @return the value of FJB_BMK.FEEMAN
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getFeeman() {
        return feeman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.FEEMAN
     *
     * @param feeman the value for FJB_BMK.FEEMAN
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setFeeman(String feeman) {
        this.feeman = feeman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.FEETIME
     *
     * @return the value of FJB_BMK.FEETIME
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getFeetime() {
        return feetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.FEETIME
     *
     * @param feetime the value for FJB_BMK.FEETIME
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setFeetime(String feetime) {
        this.feetime = feetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.CLFEES
     *
     * @return the value of FJB_BMK.CLFEES
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getClfees() {
        return clfees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.CLFEES
     *
     * @param clfees the value for FJB_BMK.CLFEES
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setClfees(String clfees) {
        this.clfees = clfees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.KSFEES
     *
     * @return the value of FJB_BMK.KSFEES
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getKsfees() {
        return ksfees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.KSFEES
     *
     * @param ksfees the value for FJB_BMK.KSFEES
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setKsfees(String ksfees) {
        this.ksfees = ksfees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.MONEYS
     *
     * @return the value of FJB_BMK.MONEYS
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getMoneys() {
        return moneys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.MONEYS
     *
     * @param moneys the value for FJB_BMK.MONEYS
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setMoneys(String moneys) {
        this.moneys = moneys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.FEESSTATUS
     *
     * @return the value of FJB_BMK.FEESSTATUS
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getFeesstatus() {
        return feesstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.FEESSTATUS
     *
     * @param feesstatus the value for FJB_BMK.FEESSTATUS
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setFeesstatus(String feesstatus) {
        this.feesstatus = feesstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.KSDQID
     *
     * @return the value of FJB_BMK.KSDQID
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public Long getKsdqid() {
        return ksdqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.KSDQID
     *
     * @param ksdqid the value for FJB_BMK.KSDQID
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setKsdqid(Long ksdqid) {
        this.ksdqid = ksdqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.KSTIME
     *
     * @return the value of FJB_BMK.KSTIME
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getKstime() {
        return kstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.KSTIME
     *
     * @param kstime the value for FJB_BMK.KSTIME
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setKstime(String kstime) {
        this.kstime = kstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.KSSOURCE
     *
     * @return the value of FJB_BMK.KSSOURCE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getKssource() {
        return kssource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.KSSOURCE
     *
     * @param kssource the value for FJB_BMK.KSSOURCE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setKssource(String kssource) {
        this.kssource = kssource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.KSADDR
     *
     * @return the value of FJB_BMK.KSADDR
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getKsaddr() {
        return ksaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.KSADDR
     *
     * @param ksaddr the value for FJB_BMK.KSADDR
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setKsaddr(String ksaddr) {
        this.ksaddr = ksaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.KCBH
     *
     * @return the value of FJB_BMK.KCBH
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getKcbh() {
        return kcbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.KCBH
     *
     * @param kcbh the value for FJB_BMK.KCBH
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setKcbh(String kcbh) {
        this.kcbh = kcbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.PCCODE
     *
     * @return the value of FJB_BMK.PCCODE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getPccode() {
        return pccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.PCCODE
     *
     * @param pccode the value for FJB_BMK.PCCODE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setPccode(String pccode) {
        this.pccode = pccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.KCH
     *
     * @return the value of FJB_BMK.KCH
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getKch() {
        return kch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.KCH
     *
     * @param kch the value for FJB_BMK.KCH
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setKch(String kch) {
        this.kch = kch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.KSDATE
     *
     * @return the value of FJB_BMK.KSDATE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getKsdate() {
        return ksdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.KSDATE
     *
     * @param ksdate the value for FJB_BMK.KSDATE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setKsdate(String ksdate) {
        this.ksdate = ksdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.KSTIMESID
     *
     * @return the value of FJB_BMK.KSTIMESID
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getKstimesid() {
        return kstimesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.KSTIMESID
     *
     * @param kstimesid the value for FJB_BMK.KSTIMESID
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setKstimesid(String kstimesid) {
        this.kstimesid = kstimesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.KSTIMES
     *
     * @return the value of FJB_BMK.KSTIMES
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getKstimes() {
        return kstimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.KSTIMES
     *
     * @param kstimes the value for FJB_BMK.KSTIMES
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setKstimes(String kstimes) {
        this.kstimes = kstimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.KSPC
     *
     * @return the value of FJB_BMK.KSPC
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getKspc() {
        return kspc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.KSPC
     *
     * @param kspc the value for FJB_BMK.KSPC
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setKspc(String kspc) {
        this.kspc = kspc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.PCID
     *
     * @return the value of FJB_BMK.PCID
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getPcid() {
        return pcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.PCID
     *
     * @param pcid the value for FJB_BMK.PCID
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setPcid(String pcid) {
        this.pcid = pcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.PXFEES
     *
     * @return the value of FJB_BMK.PXFEES
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getPxfees() {
        return pxfees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.PXFEES
     *
     * @param pxfees the value for FJB_BMK.PXFEES
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setPxfees(String pxfees) {
        this.pxfees = pxfees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.ISPX
     *
     * @return the value of FJB_BMK.ISPX
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public Long getIspx() {
        return ispx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.ISPX
     *
     * @param ispx the value for FJB_BMK.ISPX
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setIspx(Long ispx) {
        this.ispx = ispx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.PXFEEMAN
     *
     * @return the value of FJB_BMK.PXFEEMAN
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getPxfeeman() {
        return pxfeeman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.PXFEEMAN
     *
     * @param pxfeeman the value for FJB_BMK.PXFEEMAN
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setPxfeeman(String pxfeeman) {
        this.pxfeeman = pxfeeman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.PXFEEDATE
     *
     * @return the value of FJB_BMK.PXFEEDATE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getPxfeedate() {
        return pxfeedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.PXFEEDATE
     *
     * @param pxfeedate the value for FJB_BMK.PXFEEDATE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setPxfeedate(String pxfeedate) {
        this.pxfeedate = pxfeedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.PXDATE
     *
     * @return the value of FJB_BMK.PXDATE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getPxdate() {
        return pxdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.PXDATE
     *
     * @param pxdate the value for FJB_BMK.PXDATE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setPxdate(String pxdate) {
        this.pxdate = pxdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.ISPRINTPASS
     *
     * @return the value of FJB_BMK.ISPRINTPASS
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getIsprintpass() {
        return isprintpass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.ISPRINTPASS
     *
     * @param isprintpass the value for FJB_BMK.ISPRINTPASS
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setIsprintpass(String isprintpass) {
        this.isprintpass = isprintpass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.PSDATE
     *
     * @return the value of FJB_BMK.PSDATE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getPsdate() {
        return psdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.PSDATE
     *
     * @param psdate the value for FJB_BMK.PSDATE
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setPsdate(String psdate) {
        this.psdate = psdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.PSDATE2
     *
     * @return the value of FJB_BMK.PSDATE2
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getPsdate2() {
        return psdate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.PSDATE2
     *
     * @param psdate2 the value for FJB_BMK.PSDATE2
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setPsdate2(String psdate2) {
        this.psdate2 = psdate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.STATUS
     *
     * @return the value of FJB_BMK.STATUS
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.STATUS
     *
     * @param status the value for FJB_BMK.STATUS
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setStatus(Long status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.KSCOUNT
     *
     * @return the value of FJB_BMK.KSCOUNT
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public Long getKscount() {
        return kscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.KSCOUNT
     *
     * @param kscount the value for FJB_BMK.KSCOUNT
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setKscount(Long kscount) {
        this.kscount = kscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.ISZCKS
     *
     * @return the value of FJB_BMK.ISZCKS
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getIszcks() {
        return iszcks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.ISZCKS
     *
     * @param iszcks the value for FJB_BMK.ISZCKS
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setIszcks(String iszcks) {
        this.iszcks = iszcks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_BMK.KSSTATUS
     *
     * @return the value of FJB_BMK.KSSTATUS
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public String getKsstatus() {
        return ksstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_BMK.KSSTATUS
     *
     * @param ksstatus the value for FJB_BMK.KSSTATUS
     *
     * @mbg.generated Tue Jan 30 15:07:05 CST 2018
     */
    public void setKsstatus(String ksstatus) {
        this.ksstatus = ksstatus;
    }
}