package com.yinqiao.af.model;

public class ExamDate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_EXAMDATE.DATEID
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    private String dateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_EXAMDATE.EXAMDATETIME
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    private String examdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_EXAMDATE.APPLYENDDATE
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    private String applyenddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_EXAMDATE.STATUS
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_EXAMDATE.CHECKBEGIN
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    private String checkbegin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_EXAMDATE.CHECKEND
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    private String checkend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_EXAMDATE.AREAID
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    private Long areaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_EXAMDATE.ISZCKSFLAG
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    private String iszcksflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_EXAMDATE.LOGINPASS
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    private String loginpass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_EXAMDATE.BANKINFOID
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    private String bankinfoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_EXAMDATE.ADDRESS
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_EXAMDATE.PHOTOBEGINDATE
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    private String photobegindate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_EXAMDATE.PHOTOENDDATE
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    private String photoenddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_EXAMDATE.APPLYBEGINDATE
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    private String applybegindate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_EXAMDATE.DETAILDATE
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    private String detaildate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_EXAMDATE.ALLOWNUMS
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    private String allownums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_EXAMDATE.KSDQID
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    private String ksdqid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_EXAMDATE.DATEID
     *
     * @return the value of FJB_EXAMDATE.DATEID
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public String getDateid() {
        return dateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_EXAMDATE.DATEID
     *
     * @param dateid the value for FJB_EXAMDATE.DATEID
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public void setDateid(String dateid) {
        this.dateid = dateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_EXAMDATE.EXAMDATETIME
     *
     * @return the value of FJB_EXAMDATE.EXAMDATETIME
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public String getExamdatetime() {
        return examdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_EXAMDATE.EXAMDATETIME
     *
     * @param examdatetime the value for FJB_EXAMDATE.EXAMDATETIME
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public void setExamdatetime(String examdatetime) {
        this.examdatetime = examdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_EXAMDATE.APPLYENDDATE
     *
     * @return the value of FJB_EXAMDATE.APPLYENDDATE
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public String getApplyenddate() {
        return applyenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_EXAMDATE.APPLYENDDATE
     *
     * @param applyenddate the value for FJB_EXAMDATE.APPLYENDDATE
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public void setApplyenddate(String applyenddate) {
        this.applyenddate = applyenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_EXAMDATE.STATUS
     *
     * @return the value of FJB_EXAMDATE.STATUS
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_EXAMDATE.STATUS
     *
     * @param status the value for FJB_EXAMDATE.STATUS
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_EXAMDATE.CHECKBEGIN
     *
     * @return the value of FJB_EXAMDATE.CHECKBEGIN
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public String getCheckbegin() {
        return checkbegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_EXAMDATE.CHECKBEGIN
     *
     * @param checkbegin the value for FJB_EXAMDATE.CHECKBEGIN
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public void setCheckbegin(String checkbegin) {
        this.checkbegin = checkbegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_EXAMDATE.CHECKEND
     *
     * @return the value of FJB_EXAMDATE.CHECKEND
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public String getCheckend() {
        return checkend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_EXAMDATE.CHECKEND
     *
     * @param checkend the value for FJB_EXAMDATE.CHECKEND
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public void setCheckend(String checkend) {
        this.checkend = checkend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_EXAMDATE.AREAID
     *
     * @return the value of FJB_EXAMDATE.AREAID
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public Long getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_EXAMDATE.AREAID
     *
     * @param areaid the value for FJB_EXAMDATE.AREAID
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public void setAreaid(Long areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_EXAMDATE.ISZCKSFLAG
     *
     * @return the value of FJB_EXAMDATE.ISZCKSFLAG
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public String getIszcksflag() {
        return iszcksflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_EXAMDATE.ISZCKSFLAG
     *
     * @param iszcksflag the value for FJB_EXAMDATE.ISZCKSFLAG
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public void setIszcksflag(String iszcksflag) {
        this.iszcksflag = iszcksflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_EXAMDATE.LOGINPASS
     *
     * @return the value of FJB_EXAMDATE.LOGINPASS
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public String getLoginpass() {
        return loginpass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_EXAMDATE.LOGINPASS
     *
     * @param loginpass the value for FJB_EXAMDATE.LOGINPASS
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public void setLoginpass(String loginpass) {
        this.loginpass = loginpass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_EXAMDATE.BANKINFOID
     *
     * @return the value of FJB_EXAMDATE.BANKINFOID
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public String getBankinfoid() {
        return bankinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_EXAMDATE.BANKINFOID
     *
     * @param bankinfoid the value for FJB_EXAMDATE.BANKINFOID
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public void setBankinfoid(String bankinfoid) {
        this.bankinfoid = bankinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_EXAMDATE.ADDRESS
     *
     * @return the value of FJB_EXAMDATE.ADDRESS
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_EXAMDATE.ADDRESS
     *
     * @param address the value for FJB_EXAMDATE.ADDRESS
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_EXAMDATE.PHOTOBEGINDATE
     *
     * @return the value of FJB_EXAMDATE.PHOTOBEGINDATE
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public String getPhotobegindate() {
        return photobegindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_EXAMDATE.PHOTOBEGINDATE
     *
     * @param photobegindate the value for FJB_EXAMDATE.PHOTOBEGINDATE
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public void setPhotobegindate(String photobegindate) {
        this.photobegindate = photobegindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_EXAMDATE.PHOTOENDDATE
     *
     * @return the value of FJB_EXAMDATE.PHOTOENDDATE
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public String getPhotoenddate() {
        return photoenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_EXAMDATE.PHOTOENDDATE
     *
     * @param photoenddate the value for FJB_EXAMDATE.PHOTOENDDATE
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public void setPhotoenddate(String photoenddate) {
        this.photoenddate = photoenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_EXAMDATE.APPLYBEGINDATE
     *
     * @return the value of FJB_EXAMDATE.APPLYBEGINDATE
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public String getApplybegindate() {
        return applybegindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_EXAMDATE.APPLYBEGINDATE
     *
     * @param applybegindate the value for FJB_EXAMDATE.APPLYBEGINDATE
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public void setApplybegindate(String applybegindate) {
        this.applybegindate = applybegindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_EXAMDATE.DETAILDATE
     *
     * @return the value of FJB_EXAMDATE.DETAILDATE
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public String getDetaildate() {
        return detaildate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_EXAMDATE.DETAILDATE
     *
     * @param detaildate the value for FJB_EXAMDATE.DETAILDATE
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public void setDetaildate(String detaildate) {
        this.detaildate = detaildate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_EXAMDATE.ALLOWNUMS
     *
     * @return the value of FJB_EXAMDATE.ALLOWNUMS
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public String getAllownums() {
        return allownums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_EXAMDATE.ALLOWNUMS
     *
     * @param allownums the value for FJB_EXAMDATE.ALLOWNUMS
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public void setAllownums(String allownums) {
        this.allownums = allownums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_EXAMDATE.KSDQID
     *
     * @return the value of FJB_EXAMDATE.KSDQID
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public String getKsdqid() {
        return ksdqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_EXAMDATE.KSDQID
     *
     * @param ksdqid the value for FJB_EXAMDATE.KSDQID
     *
     * @mbg.generated Wed Mar 14 11:15:07 CST 2018
     */
    public void setKsdqid(String ksdqid) {
        this.ksdqid = ksdqid;
    }
}