package com.yinqiao.af.model;

import java.util.Date;

public class ExamHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_USER_EXAM_HISTORY.H_ID
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    private String hId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_USER_EXAM_HISTORY.TELNUM
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    private String telnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_USER_EXAM_HISTORY.EXAM_ID
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    private String examId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_USER_EXAM_HISTORY.EXAM_NAME
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    private String examName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_USER_EXAM_HISTORY.EXAM_TYPE
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    private String examType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_USER_EXAM_HISTORY.INDEXNUM
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    private String indexnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_USER_EXAM_HISTORY.URL
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_USER_EXAM_HISTORY.TOTALSCORE
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    private String totalscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_USER_EXAM_HISTORY.SURPLUSTIME
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    private String surplustime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_USER_EXAM_HISTORY.USEDTIME
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    private Integer usedtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_USER_EXAM_HISTORY.CREATE_TIME
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_USER_EXAM_HISTORY.UPDATE_TIME
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_USER_EXAM_HISTORY.ANSWER_RECORD
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    private String answerRecord;
    
    private String starttime;

    public String getStarttime() {
		return starttime;
	}

	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_USER_EXAM_HISTORY.H_ID
     *
     * @return the value of AF_USER_EXAM_HISTORY.H_ID
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public String gethId() {
        return hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_USER_EXAM_HISTORY.H_ID
     *
     * @param hId the value for AF_USER_EXAM_HISTORY.H_ID
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public void sethId(String hId) {
        this.hId = hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_USER_EXAM_HISTORY.TELNUM
     *
     * @return the value of AF_USER_EXAM_HISTORY.TELNUM
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public String getTelnum() {
        return telnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_USER_EXAM_HISTORY.TELNUM
     *
     * @param telnum the value for AF_USER_EXAM_HISTORY.TELNUM
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public void setTelnum(String telnum) {
        this.telnum = telnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_USER_EXAM_HISTORY.EXAM_ID
     *
     * @return the value of AF_USER_EXAM_HISTORY.EXAM_ID
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public String getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_USER_EXAM_HISTORY.EXAM_ID
     *
     * @param examId the value for AF_USER_EXAM_HISTORY.EXAM_ID
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public void setExamId(String examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_USER_EXAM_HISTORY.EXAM_NAME
     *
     * @return the value of AF_USER_EXAM_HISTORY.EXAM_NAME
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public String getExamName() {
        return examName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_USER_EXAM_HISTORY.EXAM_NAME
     *
     * @param examName the value for AF_USER_EXAM_HISTORY.EXAM_NAME
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public void setExamName(String examName) {
        this.examName = examName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_USER_EXAM_HISTORY.EXAM_TYPE
     *
     * @return the value of AF_USER_EXAM_HISTORY.EXAM_TYPE
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public String getExamType() {
        return examType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_USER_EXAM_HISTORY.EXAM_TYPE
     *
     * @param examType the value for AF_USER_EXAM_HISTORY.EXAM_TYPE
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public void setExamType(String examType) {
        this.examType = examType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_USER_EXAM_HISTORY.INDEXNUM
     *
     * @return the value of AF_USER_EXAM_HISTORY.INDEXNUM
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public String getIndexnum() {
        return indexnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_USER_EXAM_HISTORY.INDEXNUM
     *
     * @param indexnum the value for AF_USER_EXAM_HISTORY.INDEXNUM
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public void setIndexnum(String indexnum) {
        this.indexnum = indexnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_USER_EXAM_HISTORY.URL
     *
     * @return the value of AF_USER_EXAM_HISTORY.URL
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_USER_EXAM_HISTORY.URL
     *
     * @param url the value for AF_USER_EXAM_HISTORY.URL
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_USER_EXAM_HISTORY.TOTALSCORE
     *
     * @return the value of AF_USER_EXAM_HISTORY.TOTALSCORE
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public String getTotalscore() {
        return totalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_USER_EXAM_HISTORY.TOTALSCORE
     *
     * @param totalscore the value for AF_USER_EXAM_HISTORY.TOTALSCORE
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public void setTotalscore(String totalscore) {
        this.totalscore = totalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_USER_EXAM_HISTORY.SURPLUSTIME
     *
     * @return the value of AF_USER_EXAM_HISTORY.SURPLUSTIME
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public String getSurplustime() {
        return surplustime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_USER_EXAM_HISTORY.SURPLUSTIME
     *
     * @param surplustime the value for AF_USER_EXAM_HISTORY.SURPLUSTIME
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public void setSurplustime(String surplustime) {
        this.surplustime = surplustime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_USER_EXAM_HISTORY.USEDTIME
     *
     * @return the value of AF_USER_EXAM_HISTORY.USEDTIME
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public Integer getUsedtime() {
        return usedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_USER_EXAM_HISTORY.USEDTIME
     *
     * @param usedtime the value for AF_USER_EXAM_HISTORY.USEDTIME
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public void setUsedtime(Integer usedtime) {
        this.usedtime = usedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_USER_EXAM_HISTORY.CREATE_TIME
     *
     * @return the value of AF_USER_EXAM_HISTORY.CREATE_TIME
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_USER_EXAM_HISTORY.CREATE_TIME
     *
     * @param createTime the value for AF_USER_EXAM_HISTORY.CREATE_TIME
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_USER_EXAM_HISTORY.UPDATE_TIME
     *
     * @return the value of AF_USER_EXAM_HISTORY.UPDATE_TIME
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_USER_EXAM_HISTORY.UPDATE_TIME
     *
     * @param updateTime the value for AF_USER_EXAM_HISTORY.UPDATE_TIME
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_USER_EXAM_HISTORY.ANSWER_RECORD
     *
     * @return the value of AF_USER_EXAM_HISTORY.ANSWER_RECORD
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public String getAnswerRecord() {
        return answerRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_USER_EXAM_HISTORY.ANSWER_RECORD
     *
     * @param answerRecord the value for AF_USER_EXAM_HISTORY.ANSWER_RECORD
     *
     * @mbg.generated Thu Feb 08 10:50:40 CST 2018
     */
    public void setAnswerRecord(String answerRecord) {
        this.answerRecord = answerRecord;
    }
}