package com.yinqiao.af.model;

import java.util.Date;

public class ExamHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_USER_EXAM_HISTORY.H_ID
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    private String hId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_USER_EXAM_HISTORY.USER_ID
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_USER_EXAM_HISTORY.EXAM_ID
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    private String examId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_USER_EXAM_HISTORY.QUESTION_ID
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    private String questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_USER_EXAM_HISTORY.WRONG_RECORD
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    private String wrongRecord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_USER_EXAM_HISTORY.TOTALSCORE
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    private String totalscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_USER_EXAM_HISTORY.USEDTIME
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    private String usedtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_USER_EXAM_HISTORY.CREATE_TIME
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_USER_EXAM_HISTORY.UPDATE_TIME
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_USER_EXAM_HISTORY.H_ID
     *
     * @return the value of AF_USER_EXAM_HISTORY.H_ID
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    public String gethId() {
        return hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_USER_EXAM_HISTORY.H_ID
     *
     * @param hId the value for AF_USER_EXAM_HISTORY.H_ID
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    public void sethId(String hId) {
        this.hId = hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_USER_EXAM_HISTORY.USER_ID
     *
     * @return the value of AF_USER_EXAM_HISTORY.USER_ID
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_USER_EXAM_HISTORY.USER_ID
     *
     * @param userId the value for AF_USER_EXAM_HISTORY.USER_ID
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_USER_EXAM_HISTORY.EXAM_ID
     *
     * @return the value of AF_USER_EXAM_HISTORY.EXAM_ID
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    public String getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_USER_EXAM_HISTORY.EXAM_ID
     *
     * @param examId the value for AF_USER_EXAM_HISTORY.EXAM_ID
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    public void setExamId(String examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_USER_EXAM_HISTORY.QUESTION_ID
     *
     * @return the value of AF_USER_EXAM_HISTORY.QUESTION_ID
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    public String getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_USER_EXAM_HISTORY.QUESTION_ID
     *
     * @param questionId the value for AF_USER_EXAM_HISTORY.QUESTION_ID
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    public void setQuestionId(String questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_USER_EXAM_HISTORY.WRONG_RECORD
     *
     * @return the value of AF_USER_EXAM_HISTORY.WRONG_RECORD
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    public String getWrongRecord() {
        return wrongRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_USER_EXAM_HISTORY.WRONG_RECORD
     *
     * @param wrongRecord the value for AF_USER_EXAM_HISTORY.WRONG_RECORD
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    public void setWrongRecord(String wrongRecord) {
        this.wrongRecord = wrongRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_USER_EXAM_HISTORY.TOTALSCORE
     *
     * @return the value of AF_USER_EXAM_HISTORY.TOTALSCORE
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    public String getTotalscore() {
        return totalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_USER_EXAM_HISTORY.TOTALSCORE
     *
     * @param totalscore the value for AF_USER_EXAM_HISTORY.TOTALSCORE
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    public void setTotalscore(String totalscore) {
        this.totalscore = totalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_USER_EXAM_HISTORY.USEDTIME
     *
     * @return the value of AF_USER_EXAM_HISTORY.USEDTIME
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    public String getUsedtime() {
        return usedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_USER_EXAM_HISTORY.USEDTIME
     *
     * @param usedtime the value for AF_USER_EXAM_HISTORY.USEDTIME
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    public void setUsedtime(String usedtime) {
        this.usedtime = usedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_USER_EXAM_HISTORY.CREATE_TIME
     *
     * @return the value of AF_USER_EXAM_HISTORY.CREATE_TIME
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_USER_EXAM_HISTORY.CREATE_TIME
     *
     * @param createTime the value for AF_USER_EXAM_HISTORY.CREATE_TIME
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_USER_EXAM_HISTORY.UPDATE_TIME
     *
     * @return the value of AF_USER_EXAM_HISTORY.UPDATE_TIME
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_USER_EXAM_HISTORY.UPDATE_TIME
     *
     * @param updateTime the value for AF_USER_EXAM_HISTORY.UPDATE_TIME
     *
     * @mbg.generated Fri Jan 05 11:22:36 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}