package com.yinqiao.af.model;

import java.util.Date;

public class ExamList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_EXAM_LIST.EXAM_ID
     *
     * @mbg.generated Fri Jan 05 11:19:49 CST 2018
     */
    private String examId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_EXAM_LIST.NAME
     *
     * @mbg.generated Fri Jan 05 11:19:49 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_EXAM_LIST.SHOWFLAG
     *
     * @mbg.generated Fri Jan 05 11:19:49 CST 2018
     */
    private String showflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_EXAM_LIST.CREATE_TIME
     *
     * @mbg.generated Fri Jan 05 11:19:49 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_EXAM_LIST.EXAM_ID
     *
     * @return the value of AF_EXAM_LIST.EXAM_ID
     *
     * @mbg.generated Fri Jan 05 11:19:49 CST 2018
     */
    public String getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_EXAM_LIST.EXAM_ID
     *
     * @param examId the value for AF_EXAM_LIST.EXAM_ID
     *
     * @mbg.generated Fri Jan 05 11:19:49 CST 2018
     */
    public void setExamId(String examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_EXAM_LIST.NAME
     *
     * @return the value of AF_EXAM_LIST.NAME
     *
     * @mbg.generated Fri Jan 05 11:19:49 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_EXAM_LIST.NAME
     *
     * @param name the value for AF_EXAM_LIST.NAME
     *
     * @mbg.generated Fri Jan 05 11:19:49 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_EXAM_LIST.SHOWFLAG
     *
     * @return the value of AF_EXAM_LIST.SHOWFLAG
     *
     * @mbg.generated Fri Jan 05 11:19:49 CST 2018
     */
    public String getShowflag() {
        return showflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_EXAM_LIST.SHOWFLAG
     *
     * @param showflag the value for AF_EXAM_LIST.SHOWFLAG
     *
     * @mbg.generated Fri Jan 05 11:19:49 CST 2018
     */
    public void setShowflag(String showflag) {
        this.showflag = showflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_EXAM_LIST.CREATE_TIME
     *
     * @return the value of AF_EXAM_LIST.CREATE_TIME
     *
     * @mbg.generated Fri Jan 05 11:19:49 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_EXAM_LIST.CREATE_TIME
     *
     * @param createTime the value for AF_EXAM_LIST.CREATE_TIME
     *
     * @mbg.generated Fri Jan 05 11:19:49 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}