package com.yinqiao.af.model;

import java.util.Date;

public class ExamList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_EXAM_LIST.EXAM_ID
     *
     * @mbg.generated Tue Jan 30 15:51:03 CST 2018
     */
    private String examId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_EXAM_LIST.NAME
     *
     * @mbg.generated Tue Jan 30 15:51:03 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_EXAM_LIST.TOTAL_SCORE
     *
     * @mbg.generated Tue Jan 30 15:51:03 CST 2018
     */
    private String totalScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_EXAM_LIST.TOTAL_COUNT
     *
     * @mbg.generated Tue Jan 30 15:51:03 CST 2018
     */
    private String totalCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_EXAM_LIST.SHOWFLAG
     *
     * @mbg.generated Tue Jan 30 15:51:03 CST 2018
     */
    private String showflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_EXAM_LIST.INTENSIFYFLAG
     *
     * @mbg.generated Tue Jan 30 15:51:03 CST 2018
     */
    private String intensifyflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_EXAM_LIST.CREATE_TIME
     *
     * @mbg.generated Tue Jan 30 15:51:03 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_EXAM_LIST.EXAM_ID
     *
     * @return the value of AF_EXAM_LIST.EXAM_ID
     *
     * @mbg.generated Tue Jan 30 15:51:03 CST 2018
     */
    public String getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_EXAM_LIST.EXAM_ID
     *
     * @param examId the value for AF_EXAM_LIST.EXAM_ID
     *
     * @mbg.generated Tue Jan 30 15:51:03 CST 2018
     */
    public void setExamId(String examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_EXAM_LIST.NAME
     *
     * @return the value of AF_EXAM_LIST.NAME
     *
     * @mbg.generated Tue Jan 30 15:51:03 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_EXAM_LIST.NAME
     *
     * @param name the value for AF_EXAM_LIST.NAME
     *
     * @mbg.generated Tue Jan 30 15:51:03 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_EXAM_LIST.TOTAL_SCORE
     *
     * @return the value of AF_EXAM_LIST.TOTAL_SCORE
     *
     * @mbg.generated Tue Jan 30 15:51:03 CST 2018
     */
    public String getTotalScore() {
        return totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_EXAM_LIST.TOTAL_SCORE
     *
     * @param totalScore the value for AF_EXAM_LIST.TOTAL_SCORE
     *
     * @mbg.generated Tue Jan 30 15:51:03 CST 2018
     */
    public void setTotalScore(String totalScore) {
        this.totalScore = totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_EXAM_LIST.TOTAL_COUNT
     *
     * @return the value of AF_EXAM_LIST.TOTAL_COUNT
     *
     * @mbg.generated Tue Jan 30 15:51:03 CST 2018
     */
    public String getTotalCount() {
        return totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_EXAM_LIST.TOTAL_COUNT
     *
     * @param totalCount the value for AF_EXAM_LIST.TOTAL_COUNT
     *
     * @mbg.generated Tue Jan 30 15:51:03 CST 2018
     */
    public void setTotalCount(String totalCount) {
        this.totalCount = totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_EXAM_LIST.SHOWFLAG
     *
     * @return the value of AF_EXAM_LIST.SHOWFLAG
     *
     * @mbg.generated Tue Jan 30 15:51:03 CST 2018
     */
    public String getShowflag() {
        return showflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_EXAM_LIST.SHOWFLAG
     *
     * @param showflag the value for AF_EXAM_LIST.SHOWFLAG
     *
     * @mbg.generated Tue Jan 30 15:51:03 CST 2018
     */
    public void setShowflag(String showflag) {
        this.showflag = showflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_EXAM_LIST.INTENSIFYFLAG
     *
     * @return the value of AF_EXAM_LIST.INTENSIFYFLAG
     *
     * @mbg.generated Tue Jan 30 15:51:03 CST 2018
     */
    public String getIntensifyflag() {
        return intensifyflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_EXAM_LIST.INTENSIFYFLAG
     *
     * @param intensifyflag the value for AF_EXAM_LIST.INTENSIFYFLAG
     *
     * @mbg.generated Tue Jan 30 15:51:03 CST 2018
     */
    public void setIntensifyflag(String intensifyflag) {
        this.intensifyflag = intensifyflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_EXAM_LIST.CREATE_TIME
     *
     * @return the value of AF_EXAM_LIST.CREATE_TIME
     *
     * @mbg.generated Tue Jan 30 15:51:03 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_EXAM_LIST.CREATE_TIME
     *
     * @param createTime the value for AF_EXAM_LIST.CREATE_TIME
     *
     * @mbg.generated Tue Jan 30 15:51:03 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}