package com.yinqiao.af.model;

public class Grade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_GRADE.GRADEID
     *
     * @mbg.generated Sun Jan 21 10:59:04 CST 2018
     */
    private Long gradeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_GRADE.IDCARD
     *
     * @mbg.generated Sun Jan 21 10:59:04 CST 2018
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_GRADE.ZKZH
     *
     * @mbg.generated Sun Jan 21 10:59:04 CST 2018
     */
    private String zkzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_GRADE.KSTIME
     *
     * @mbg.generated Sun Jan 21 10:59:04 CST 2018
     */
    private String kstime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_GRADE.GRADE
     *
     * @mbg.generated Sun Jan 21 10:59:04 CST 2018
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_GRADE.LLGRADE
     *
     * @mbg.generated Sun Jan 21 10:59:04 CST 2018
     */
    private String llgrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_GRADE.SCGRADE
     *
     * @mbg.generated Sun Jan 21 10:59:04 CST 2018
     */
    private String scgrade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_GRADE.GRADEID
     *
     * @return the value of FJB_GRADE.GRADEID
     *
     * @mbg.generated Sun Jan 21 10:59:04 CST 2018
     */
    private String keepTime;
    
    public Long getGradeid() {
        return gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_GRADE.GRADEID
     *
     * @param gradeid the value for FJB_GRADE.GRADEID
     *
     * @mbg.generated Sun Jan 21 10:59:04 CST 2018
     */
    public void setGradeid(Long gradeid) {
        this.gradeid = gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_GRADE.IDCARD
     *
     * @return the value of FJB_GRADE.IDCARD
     *
     * @mbg.generated Sun Jan 21 10:59:04 CST 2018
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_GRADE.IDCARD
     *
     * @param idcard the value for FJB_GRADE.IDCARD
     *
     * @mbg.generated Sun Jan 21 10:59:04 CST 2018
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_GRADE.ZKZH
     *
     * @return the value of FJB_GRADE.ZKZH
     *
     * @mbg.generated Sun Jan 21 10:59:04 CST 2018
     */
    public String getZkzh() {
        return zkzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_GRADE.ZKZH
     *
     * @param zkzh the value for FJB_GRADE.ZKZH
     *
     * @mbg.generated Sun Jan 21 10:59:04 CST 2018
     */
    public void setZkzh(String zkzh) {
        this.zkzh = zkzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_GRADE.KSTIME
     *
     * @return the value of FJB_GRADE.KSTIME
     *
     * @mbg.generated Sun Jan 21 10:59:04 CST 2018
     */
    public String getKstime() {
        return kstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_GRADE.KSTIME
     *
     * @param kstime the value for FJB_GRADE.KSTIME
     *
     * @mbg.generated Sun Jan 21 10:59:04 CST 2018
     */
    public void setKstime(String kstime) {
        this.kstime = kstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_GRADE.GRADE
     *
     * @return the value of FJB_GRADE.GRADE
     *
     * @mbg.generated Sun Jan 21 10:59:04 CST 2018
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_GRADE.GRADE
     *
     * @param grade the value for FJB_GRADE.GRADE
     *
     * @mbg.generated Sun Jan 21 10:59:04 CST 2018
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_GRADE.LLGRADE
     *
     * @return the value of FJB_GRADE.LLGRADE
     *
     * @mbg.generated Sun Jan 21 10:59:04 CST 2018
     */
    public String getLlgrade() {
        return llgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_GRADE.LLGRADE
     *
     * @param llgrade the value for FJB_GRADE.LLGRADE
     *
     * @mbg.generated Sun Jan 21 10:59:04 CST 2018
     */
    public void setLlgrade(String llgrade) {
        this.llgrade = llgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_GRADE.SCGRADE
     *
     * @return the value of FJB_GRADE.SCGRADE
     *
     * @mbg.generated Sun Jan 21 10:59:04 CST 2018
     */
    public String getScgrade() {
        return scgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_GRADE.SCGRADE
     *
     * @param scgrade the value for FJB_GRADE.SCGRADE
     *
     * @mbg.generated Sun Jan 21 10:59:04 CST 2018
     */
    public void setScgrade(String scgrade) {
        this.scgrade = scgrade;
    }

	public String getKeepTime() {
		return keepTime;
	}

	public void setKeepTime(String keepTime) {
		this.keepTime = keepTime;
	}
}