package com.yinqiao.af.model;

public class NationInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_NATION.NATIONID
     *
     * @mbg.generated Wed Mar 14 09:45:11 CST 2018
     */
    private String nationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_NATION.NATIONNAME
     *
     * @mbg.generated Wed Mar 14 09:45:11 CST 2018
     */
    private String nationname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJB_NATION.STATUS
     *
     * @mbg.generated Wed Mar 14 09:45:11 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_NATION.NATIONID
     *
     * @return the value of FJB_NATION.NATIONID
     *
     * @mbg.generated Wed Mar 14 09:45:11 CST 2018
     */
    public String getNationid() {
        return nationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_NATION.NATIONID
     *
     * @param nationid the value for FJB_NATION.NATIONID
     *
     * @mbg.generated Wed Mar 14 09:45:11 CST 2018
     */
    public void setNationid(String nationid) {
        this.nationid = nationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_NATION.NATIONNAME
     *
     * @return the value of FJB_NATION.NATIONNAME
     *
     * @mbg.generated Wed Mar 14 09:45:11 CST 2018
     */
    public String getNationname() {
        return nationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_NATION.NATIONNAME
     *
     * @param nationname the value for FJB_NATION.NATIONNAME
     *
     * @mbg.generated Wed Mar 14 09:45:11 CST 2018
     */
    public void setNationname(String nationname) {
        this.nationname = nationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJB_NATION.STATUS
     *
     * @return the value of FJB_NATION.STATUS
     *
     * @mbg.generated Wed Mar 14 09:45:11 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJB_NATION.STATUS
     *
     * @param status the value for FJB_NATION.STATUS
     *
     * @mbg.generated Wed Mar 14 09:45:11 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }
}