package com.yinqiao.af.model;

import java.util.Date;

public class OrderInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_ORDER_INFO.ORDER_ID
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_ORDER_INFO.PRODUCT_ID
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_ORDER_INFO.PRODUCT_NAME
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_ORDER_INFO.TELNUM
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    private String telnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_ORDER_INFO.OPENID
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_ORDER_INFO.AMOUNT
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    private String amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_ORDER_INFO.STATUS
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_ORDER_INFO.TRADE_NO
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    private String tradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_ORDER_INFO.PAYTIME
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    private Date paytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_ORDER_INFO.CREATE_TIME
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    private Date createTime;
    
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_ORDER_INFO.ORDER_ID
     *
     * @return the value of AF_ORDER_INFO.ORDER_ID
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_ORDER_INFO.ORDER_ID
     *
     * @param orderId the value for AF_ORDER_INFO.ORDER_ID
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_ORDER_INFO.PRODUCT_ID
     *
     * @return the value of AF_ORDER_INFO.PRODUCT_ID
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_ORDER_INFO.PRODUCT_ID
     *
     * @param productId the value for AF_ORDER_INFO.PRODUCT_ID
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_ORDER_INFO.PRODUCT_NAME
     *
     * @return the value of AF_ORDER_INFO.PRODUCT_NAME
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_ORDER_INFO.PRODUCT_NAME
     *
     * @param productName the value for AF_ORDER_INFO.PRODUCT_NAME
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_ORDER_INFO.TELNUM
     *
     * @return the value of AF_ORDER_INFO.TELNUM
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    public String getTelnum() {
        return telnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_ORDER_INFO.TELNUM
     *
     * @param telnum the value for AF_ORDER_INFO.TELNUM
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    public void setTelnum(String telnum) {
        this.telnum = telnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_ORDER_INFO.OPENID
     *
     * @return the value of AF_ORDER_INFO.OPENID
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_ORDER_INFO.OPENID
     *
     * @param openid the value for AF_ORDER_INFO.OPENID
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_ORDER_INFO.AMOUNT
     *
     * @return the value of AF_ORDER_INFO.AMOUNT
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_ORDER_INFO.AMOUNT
     *
     * @param amount the value for AF_ORDER_INFO.AMOUNT
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    public void setAmount(String amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_ORDER_INFO.STATUS
     *
     * @return the value of AF_ORDER_INFO.STATUS
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_ORDER_INFO.STATUS
     *
     * @param status the value for AF_ORDER_INFO.STATUS
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_ORDER_INFO.TRADE_NO
     *
     * @return the value of AF_ORDER_INFO.TRADE_NO
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_ORDER_INFO.TRADE_NO
     *
     * @param tradeNo the value for AF_ORDER_INFO.TRADE_NO
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_ORDER_INFO.PAYTIME
     *
     * @return the value of AF_ORDER_INFO.PAYTIME
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_ORDER_INFO.PAYTIME
     *
     * @param paytime the value for AF_ORDER_INFO.PAYTIME
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_ORDER_INFO.CREATE_TIME
     *
     * @return the value of AF_ORDER_INFO.CREATE_TIME
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_ORDER_INFO.CREATE_TIME
     *
     * @param createTime the value for AF_ORDER_INFO.CREATE_TIME
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
}