package com.yinqiao.af.model;

import java.util.Date;

public class PayDetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_PAY_DETAIL.ORDERID
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	private String orderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_PAY_DETAIL.ORDER_TYPE
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	private String orderType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_PAY_DETAIL.PHONE
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_PAY_DETAIL.PAY_ORGA
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	private String payOrga;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_PAY_DETAIL.CHANNEL
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	private String channel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_PAY_DETAIL.AMOUNT
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	private Integer amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_PAY_DETAIL.DESCRIPTION
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_PAY_DETAIL.STATUS
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_PAY_DETAIL.STATUS_TIME
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	private Date statusTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_PAY_DETAIL.PAY_TIME
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	private Date payTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_PAY_DETAIL.TRADE_NO
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	private String tradeNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_PAY_DETAIL.CREATE_TIME
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_PAY_DETAIL.UPDATE_TIME
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_PAY_DETAIL.ORDERID
	 * @return  the value of T_PAY_DETAIL.ORDERID
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public String getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_PAY_DETAIL.ORDERID
	 * @param orderid  the value for T_PAY_DETAIL.ORDERID
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_PAY_DETAIL.ORDER_TYPE
	 * @return  the value of T_PAY_DETAIL.ORDER_TYPE
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public String getOrderType() {
		return orderType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_PAY_DETAIL.ORDER_TYPE
	 * @param orderType  the value for T_PAY_DETAIL.ORDER_TYPE
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_PAY_DETAIL.PHONE
	 * @return  the value of T_PAY_DETAIL.PHONE
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_PAY_DETAIL.PHONE
	 * @param phone  the value for T_PAY_DETAIL.PHONE
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_PAY_DETAIL.PAY_ORGA
	 * @return  the value of T_PAY_DETAIL.PAY_ORGA
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public String getPayOrga() {
		return payOrga;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_PAY_DETAIL.PAY_ORGA
	 * @param payOrga  the value for T_PAY_DETAIL.PAY_ORGA
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public void setPayOrga(String payOrga) {
		this.payOrga = payOrga;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_PAY_DETAIL.CHANNEL
	 * @return  the value of T_PAY_DETAIL.CHANNEL
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public String getChannel() {
		return channel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_PAY_DETAIL.CHANNEL
	 * @param channel  the value for T_PAY_DETAIL.CHANNEL
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public void setChannel(String channel) {
		this.channel = channel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_PAY_DETAIL.AMOUNT
	 * @return  the value of T_PAY_DETAIL.AMOUNT
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public Integer getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_PAY_DETAIL.AMOUNT
	 * @param amount  the value for T_PAY_DETAIL.AMOUNT
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_PAY_DETAIL.DESCRIPTION
	 * @return  the value of T_PAY_DETAIL.DESCRIPTION
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_PAY_DETAIL.DESCRIPTION
	 * @param description  the value for T_PAY_DETAIL.DESCRIPTION
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_PAY_DETAIL.STATUS
	 * @return  the value of T_PAY_DETAIL.STATUS
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_PAY_DETAIL.STATUS
	 * @param status  the value for T_PAY_DETAIL.STATUS
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_PAY_DETAIL.STATUS_TIME
	 * @return  the value of T_PAY_DETAIL.STATUS_TIME
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public Date getStatusTime() {
		return statusTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_PAY_DETAIL.STATUS_TIME
	 * @param statusTime  the value for T_PAY_DETAIL.STATUS_TIME
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public void setStatusTime(Date statusTime) {
		this.statusTime = statusTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_PAY_DETAIL.PAY_TIME
	 * @return  the value of T_PAY_DETAIL.PAY_TIME
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public Date getPayTime() {
		return payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_PAY_DETAIL.PAY_TIME
	 * @param payTime  the value for T_PAY_DETAIL.PAY_TIME
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_PAY_DETAIL.TRADE_NO
	 * @return  the value of T_PAY_DETAIL.TRADE_NO
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public String getTradeNo() {
		return tradeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_PAY_DETAIL.TRADE_NO
	 * @param tradeNo  the value for T_PAY_DETAIL.TRADE_NO
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public void setTradeNo(String tradeNo) {
		this.tradeNo = tradeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_PAY_DETAIL.CREATE_TIME
	 * @return  the value of T_PAY_DETAIL.CREATE_TIME
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_PAY_DETAIL.CREATE_TIME
	 * @param createTime  the value for T_PAY_DETAIL.CREATE_TIME
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_PAY_DETAIL.UPDATE_TIME
	 * @return  the value of T_PAY_DETAIL.UPDATE_TIME
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_PAY_DETAIL.UPDATE_TIME
	 * @param updateTime  the value for T_PAY_DETAIL.UPDATE_TIME
	 * @mbggenerated  Fri Nov 10 17:10:15 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}