package com.yinqiao.af.model;

import java.util.Date;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Mon Jan 29 16:58:50 CST 2018
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_PRODUCT.PRODUCT_NAME
     *
     * @mbg.generated Mon Jan 29 16:58:50 CST 2018
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_PRODUCT.UNIT
     *
     * @mbg.generated Mon Jan 29 16:58:50 CST 2018
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_PRODUCT.AMOUNT
     *
     * @mbg.generated Mon Jan 29 16:58:50 CST 2018
     */
    private String amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_PRODUCT.DESCRIPTION
     *
     * @mbg.generated Mon Jan 29 16:58:50 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_PRODUCT.ENDTIME
     *
     * @mbg.generated Mon Jan 29 16:58:50 CST 2018
     */
    private Date endtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_PRODUCT.PRODUCT_ID
     *
     * @return the value of AF_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Mon Jan 29 16:58:50 CST 2018
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_PRODUCT.PRODUCT_ID
     *
     * @param productId the value for AF_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Mon Jan 29 16:58:50 CST 2018
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_PRODUCT.PRODUCT_NAME
     *
     * @return the value of AF_PRODUCT.PRODUCT_NAME
     *
     * @mbg.generated Mon Jan 29 16:58:50 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_PRODUCT.PRODUCT_NAME
     *
     * @param productName the value for AF_PRODUCT.PRODUCT_NAME
     *
     * @mbg.generated Mon Jan 29 16:58:50 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_PRODUCT.UNIT
     *
     * @return the value of AF_PRODUCT.UNIT
     *
     * @mbg.generated Mon Jan 29 16:58:50 CST 2018
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_PRODUCT.UNIT
     *
     * @param unit the value for AF_PRODUCT.UNIT
     *
     * @mbg.generated Mon Jan 29 16:58:50 CST 2018
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_PRODUCT.AMOUNT
     *
     * @return the value of AF_PRODUCT.AMOUNT
     *
     * @mbg.generated Mon Jan 29 16:58:50 CST 2018
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_PRODUCT.AMOUNT
     *
     * @param amount the value for AF_PRODUCT.AMOUNT
     *
     * @mbg.generated Mon Jan 29 16:58:50 CST 2018
     */
    public void setAmount(String amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_PRODUCT.DESCRIPTION
     *
     * @return the value of AF_PRODUCT.DESCRIPTION
     *
     * @mbg.generated Mon Jan 29 16:58:50 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_PRODUCT.DESCRIPTION
     *
     * @param description the value for AF_PRODUCT.DESCRIPTION
     *
     * @mbg.generated Mon Jan 29 16:58:50 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_PRODUCT.ENDTIME
     *
     * @return the value of AF_PRODUCT.ENDTIME
     *
     * @mbg.generated Mon Jan 29 16:58:50 CST 2018
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_PRODUCT.ENDTIME
     *
     * @param endtime the value for AF_PRODUCT.ENDTIME
     *
     * @mbg.generated Mon Jan 29 16:58:50 CST 2018
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }
}