package com.yinqiao.af.model;

public class QuestionBank {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_QUESTION_BANK.QUESTION_ID
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    private String questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_QUESTION_BANK.EXAM_ID
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    private String examId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_QUESTION_BANK.TYPE
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_QUESTION_BANK.CONTENT
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_QUESTION_BANK.PICFLAG
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    private String picflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_QUESTION_BANK.ANSWER
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_QUESTION_BANK.STANDARD
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    private String standard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_QUESTION_BANK.SCORE
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    private String score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_QUESTION_BANK.QUESTION_ID
     *
     * @return the value of AF_QUESTION_BANK.QUESTION_ID
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    public String getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_QUESTION_BANK.QUESTION_ID
     *
     * @param questionId the value for AF_QUESTION_BANK.QUESTION_ID
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    public void setQuestionId(String questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_QUESTION_BANK.EXAM_ID
     *
     * @return the value of AF_QUESTION_BANK.EXAM_ID
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    public String getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_QUESTION_BANK.EXAM_ID
     *
     * @param examId the value for AF_QUESTION_BANK.EXAM_ID
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    public void setExamId(String examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_QUESTION_BANK.TYPE
     *
     * @return the value of AF_QUESTION_BANK.TYPE
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_QUESTION_BANK.TYPE
     *
     * @param type the value for AF_QUESTION_BANK.TYPE
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_QUESTION_BANK.CONTENT
     *
     * @return the value of AF_QUESTION_BANK.CONTENT
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_QUESTION_BANK.CONTENT
     *
     * @param content the value for AF_QUESTION_BANK.CONTENT
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_QUESTION_BANK.PICFLAG
     *
     * @return the value of AF_QUESTION_BANK.PICFLAG
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    public String getPicflag() {
        return picflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_QUESTION_BANK.PICFLAG
     *
     * @param picflag the value for AF_QUESTION_BANK.PICFLAG
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    public void setPicflag(String picflag) {
        this.picflag = picflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_QUESTION_BANK.ANSWER
     *
     * @return the value of AF_QUESTION_BANK.ANSWER
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_QUESTION_BANK.ANSWER
     *
     * @param answer the value for AF_QUESTION_BANK.ANSWER
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_QUESTION_BANK.STANDARD
     *
     * @return the value of AF_QUESTION_BANK.STANDARD
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_QUESTION_BANK.STANDARD
     *
     * @param standard the value for AF_QUESTION_BANK.STANDARD
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    public void setStandard(String standard) {
        this.standard = standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_QUESTION_BANK.SCORE
     *
     * @return the value of AF_QUESTION_BANK.SCORE
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_QUESTION_BANK.SCORE
     *
     * @param score the value for AF_QUESTION_BANK.SCORE
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    public void setScore(String score) {
        this.score = score;
    }
}