package com.yinqiao.af.model;

public class QuestionnaireModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.TESTID
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String testid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.WJNUMS
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String wjnums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.TESTTYPE
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String testtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.TESTTITLE
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String testtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.CHOICE1
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String choice1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.CHOICE2
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String choice2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.CHOICE3
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String choice3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.CHOICE4
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String choice4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.CHOICE5
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String choice5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.CHOICE6
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String choice6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.CHOICE7
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String choice7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.CHOICE8
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String choice8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.CHOICE9
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String choice9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.CHOICE10
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String choice10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.CHOICE11
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String choice11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.CHOICE12
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String choice12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.CHOICE13
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String choice13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.CHOICE14
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String choice14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.CHOICE15
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String choice15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.CHOICENUMS
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String choicenums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.IMAGEFLAG
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String imageflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.LIMITMIN
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String limitmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.LIMITMAX
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String limitmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_TEST.MUTEXNUM
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    private String mutexnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.TESTID
     *
     * @return the value of WJ_TEST.TESTID
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getTestid() {
        return testid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.TESTID
     *
     * @param testid the value for WJ_TEST.TESTID
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setTestid(String testid) {
        this.testid = testid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.WJNUMS
     *
     * @return the value of WJ_TEST.WJNUMS
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getWjnums() {
        return wjnums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.WJNUMS
     *
     * @param wjnums the value for WJ_TEST.WJNUMS
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setWjnums(String wjnums) {
        this.wjnums = wjnums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.TESTTYPE
     *
     * @return the value of WJ_TEST.TESTTYPE
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getTesttype() {
        return testtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.TESTTYPE
     *
     * @param testtype the value for WJ_TEST.TESTTYPE
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setTesttype(String testtype) {
        this.testtype = testtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.TESTTITLE
     *
     * @return the value of WJ_TEST.TESTTITLE
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getTesttitle() {
        return testtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.TESTTITLE
     *
     * @param testtitle the value for WJ_TEST.TESTTITLE
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setTesttitle(String testtitle) {
        this.testtitle = testtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.CHOICE1
     *
     * @return the value of WJ_TEST.CHOICE1
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getChoice1() {
        return choice1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.CHOICE1
     *
     * @param choice1 the value for WJ_TEST.CHOICE1
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setChoice1(String choice1) {
        this.choice1 = choice1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.CHOICE2
     *
     * @return the value of WJ_TEST.CHOICE2
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getChoice2() {
        return choice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.CHOICE2
     *
     * @param choice2 the value for WJ_TEST.CHOICE2
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setChoice2(String choice2) {
        this.choice2 = choice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.CHOICE3
     *
     * @return the value of WJ_TEST.CHOICE3
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getChoice3() {
        return choice3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.CHOICE3
     *
     * @param choice3 the value for WJ_TEST.CHOICE3
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setChoice3(String choice3) {
        this.choice3 = choice3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.CHOICE4
     *
     * @return the value of WJ_TEST.CHOICE4
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getChoice4() {
        return choice4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.CHOICE4
     *
     * @param choice4 the value for WJ_TEST.CHOICE4
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setChoice4(String choice4) {
        this.choice4 = choice4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.CHOICE5
     *
     * @return the value of WJ_TEST.CHOICE5
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getChoice5() {
        return choice5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.CHOICE5
     *
     * @param choice5 the value for WJ_TEST.CHOICE5
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setChoice5(String choice5) {
        this.choice5 = choice5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.CHOICE6
     *
     * @return the value of WJ_TEST.CHOICE6
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getChoice6() {
        return choice6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.CHOICE6
     *
     * @param choice6 the value for WJ_TEST.CHOICE6
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setChoice6(String choice6) {
        this.choice6 = choice6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.CHOICE7
     *
     * @return the value of WJ_TEST.CHOICE7
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getChoice7() {
        return choice7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.CHOICE7
     *
     * @param choice7 the value for WJ_TEST.CHOICE7
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setChoice7(String choice7) {
        this.choice7 = choice7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.CHOICE8
     *
     * @return the value of WJ_TEST.CHOICE8
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getChoice8() {
        return choice8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.CHOICE8
     *
     * @param choice8 the value for WJ_TEST.CHOICE8
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setChoice8(String choice8) {
        this.choice8 = choice8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.CHOICE9
     *
     * @return the value of WJ_TEST.CHOICE9
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getChoice9() {
        return choice9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.CHOICE9
     *
     * @param choice9 the value for WJ_TEST.CHOICE9
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setChoice9(String choice9) {
        this.choice9 = choice9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.CHOICE10
     *
     * @return the value of WJ_TEST.CHOICE10
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getChoice10() {
        return choice10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.CHOICE10
     *
     * @param choice10 the value for WJ_TEST.CHOICE10
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setChoice10(String choice10) {
        this.choice10 = choice10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.CHOICE11
     *
     * @return the value of WJ_TEST.CHOICE11
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getChoice11() {
        return choice11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.CHOICE11
     *
     * @param choice11 the value for WJ_TEST.CHOICE11
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setChoice11(String choice11) {
        this.choice11 = choice11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.CHOICE12
     *
     * @return the value of WJ_TEST.CHOICE12
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getChoice12() {
        return choice12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.CHOICE12
     *
     * @param choice12 the value for WJ_TEST.CHOICE12
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setChoice12(String choice12) {
        this.choice12 = choice12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.CHOICE13
     *
     * @return the value of WJ_TEST.CHOICE13
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getChoice13() {
        return choice13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.CHOICE13
     *
     * @param choice13 the value for WJ_TEST.CHOICE13
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setChoice13(String choice13) {
        this.choice13 = choice13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.CHOICE14
     *
     * @return the value of WJ_TEST.CHOICE14
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getChoice14() {
        return choice14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.CHOICE14
     *
     * @param choice14 the value for WJ_TEST.CHOICE14
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setChoice14(String choice14) {
        this.choice14 = choice14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.CHOICE15
     *
     * @return the value of WJ_TEST.CHOICE15
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getChoice15() {
        return choice15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.CHOICE15
     *
     * @param choice15 the value for WJ_TEST.CHOICE15
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setChoice15(String choice15) {
        this.choice15 = choice15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.CHOICENUMS
     *
     * @return the value of WJ_TEST.CHOICENUMS
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getChoicenums() {
        return choicenums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.CHOICENUMS
     *
     * @param choicenums the value for WJ_TEST.CHOICENUMS
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setChoicenums(String choicenums) {
        this.choicenums = choicenums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.IMAGEFLAG
     *
     * @return the value of WJ_TEST.IMAGEFLAG
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getImageflag() {
        return imageflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.IMAGEFLAG
     *
     * @param imageflag the value for WJ_TEST.IMAGEFLAG
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setImageflag(String imageflag) {
        this.imageflag = imageflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.LIMITMIN
     *
     * @return the value of WJ_TEST.LIMITMIN
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getLimitmin() {
        return limitmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.LIMITMIN
     *
     * @param limitmin the value for WJ_TEST.LIMITMIN
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setLimitmin(String limitmin) {
        this.limitmin = limitmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.LIMITMAX
     *
     * @return the value of WJ_TEST.LIMITMAX
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getLimitmax() {
        return limitmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.LIMITMAX
     *
     * @param limitmax the value for WJ_TEST.LIMITMAX
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setLimitmax(String limitmax) {
        this.limitmax = limitmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_TEST.MUTEXNUM
     *
     * @return the value of WJ_TEST.MUTEXNUM
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public String getMutexnum() {
        return mutexnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_TEST.MUTEXNUM
     *
     * @param mutexnum the value for WJ_TEST.MUTEXNUM
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    public void setMutexnum(String mutexnum) {
        this.mutexnum = mutexnum;
    }
}