package com.yinqiao.af.model;

public class QuestionnaireLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_LOGS.LOGSID
     *
     * @mbg.generated Fri May 25 16:20:42 CST 2018
     */
    private String logsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_LOGS.QUESTIONID
     *
     * @mbg.generated Fri May 25 16:20:42 CST 2018
     */
    private String questionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_LOGS.TESTID
     *
     * @mbg.generated Fri May 25 16:20:42 CST 2018
     */
    private String testid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_LOGS.TESTANSWER
     *
     * @mbg.generated Fri May 25 16:20:42 CST 2018
     */
    private String testanswer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WJ_LOGS.WJNUMS
     *
     * @mbg.generated Fri May 25 16:20:42 CST 2018
     */
    private String wjnums;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_LOGS.LOGSID
     *
     * @return the value of WJ_LOGS.LOGSID
     *
     * @mbg.generated Fri May 25 16:20:42 CST 2018
     */
    public String getLogsid() {
        return logsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_LOGS.LOGSID
     *
     * @param logsid the value for WJ_LOGS.LOGSID
     *
     * @mbg.generated Fri May 25 16:20:42 CST 2018
     */
    public void setLogsid(String logsid) {
        this.logsid = logsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_LOGS.QUESTIONID
     *
     * @return the value of WJ_LOGS.QUESTIONID
     *
     * @mbg.generated Fri May 25 16:20:42 CST 2018
     */
    public String getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_LOGS.QUESTIONID
     *
     * @param questionid the value for WJ_LOGS.QUESTIONID
     *
     * @mbg.generated Fri May 25 16:20:42 CST 2018
     */
    public void setQuestionid(String questionid) {
        this.questionid = questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_LOGS.TESTID
     *
     * @return the value of WJ_LOGS.TESTID
     *
     * @mbg.generated Fri May 25 16:20:42 CST 2018
     */
    public String getTestid() {
        return testid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_LOGS.TESTID
     *
     * @param testid the value for WJ_LOGS.TESTID
     *
     * @mbg.generated Fri May 25 16:20:42 CST 2018
     */
    public void setTestid(String testid) {
        this.testid = testid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_LOGS.TESTANSWER
     *
     * @return the value of WJ_LOGS.TESTANSWER
     *
     * @mbg.generated Fri May 25 16:20:42 CST 2018
     */
    public String getTestanswer() {
        return testanswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_LOGS.TESTANSWER
     *
     * @param testanswer the value for WJ_LOGS.TESTANSWER
     *
     * @mbg.generated Fri May 25 16:20:42 CST 2018
     */
    public void setTestanswer(String testanswer) {
        this.testanswer = testanswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WJ_LOGS.WJNUMS
     *
     * @return the value of WJ_LOGS.WJNUMS
     *
     * @mbg.generated Fri May 25 16:20:42 CST 2018
     */
    public String getWjnums() {
        return wjnums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WJ_LOGS.WJNUMS
     *
     * @param wjnums the value for WJ_LOGS.WJNUMS
     *
     * @mbg.generated Fri May 25 16:20:42 CST 2018
     */
    public void setWjnums(String wjnums) {
        this.wjnums = wjnums;
    }
}