package com.yinqiao.af.model;

public class RegionInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_REGION_INFO.DIQUID
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    private String diquid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_REGION_INFO.DIQUNAME
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    private String diquname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_REGION_INFO.ZONEID
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    private String zoneid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_REGION_INFO.ZONENAME
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    private String zonename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_REGION_INFO.BANKTYPE
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    private String banktype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_REGION_INFO.BANKTYPENAME
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    private String banktypename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_REGION_INFO.BANKID
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    private String bankid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AF_REGION_INFO.BANKNAME
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    private String bankname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_REGION_INFO.DIQUID
     *
     * @return the value of AF_REGION_INFO.DIQUID
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    public String getDiquid() {
        return diquid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_REGION_INFO.DIQUID
     *
     * @param diquid the value for AF_REGION_INFO.DIQUID
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    public void setDiquid(String diquid) {
        this.diquid = diquid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_REGION_INFO.DIQUNAME
     *
     * @return the value of AF_REGION_INFO.DIQUNAME
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    public String getDiquname() {
        return diquname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_REGION_INFO.DIQUNAME
     *
     * @param diquname the value for AF_REGION_INFO.DIQUNAME
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    public void setDiquname(String diquname) {
        this.diquname = diquname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_REGION_INFO.ZONEID
     *
     * @return the value of AF_REGION_INFO.ZONEID
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    public String getZoneid() {
        return zoneid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_REGION_INFO.ZONEID
     *
     * @param zoneid the value for AF_REGION_INFO.ZONEID
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    public void setZoneid(String zoneid) {
        this.zoneid = zoneid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_REGION_INFO.ZONENAME
     *
     * @return the value of AF_REGION_INFO.ZONENAME
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    public String getZonename() {
        return zonename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_REGION_INFO.ZONENAME
     *
     * @param zonename the value for AF_REGION_INFO.ZONENAME
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    public void setZonename(String zonename) {
        this.zonename = zonename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_REGION_INFO.BANKTYPE
     *
     * @return the value of AF_REGION_INFO.BANKTYPE
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    public String getBanktype() {
        return banktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_REGION_INFO.BANKTYPE
     *
     * @param banktype the value for AF_REGION_INFO.BANKTYPE
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    public void setBanktype(String banktype) {
        this.banktype = banktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_REGION_INFO.BANKTYPENAME
     *
     * @return the value of AF_REGION_INFO.BANKTYPENAME
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    public String getBanktypename() {
        return banktypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_REGION_INFO.BANKTYPENAME
     *
     * @param banktypename the value for AF_REGION_INFO.BANKTYPENAME
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    public void setBanktypename(String banktypename) {
        this.banktypename = banktypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_REGION_INFO.BANKID
     *
     * @return the value of AF_REGION_INFO.BANKID
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    public String getBankid() {
        return bankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_REGION_INFO.BANKID
     *
     * @param bankid the value for AF_REGION_INFO.BANKID
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    public void setBankid(String bankid) {
        this.bankid = bankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AF_REGION_INFO.BANKNAME
     *
     * @return the value of AF_REGION_INFO.BANKNAME
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AF_REGION_INFO.BANKNAME
     *
     * @param bankname the value for AF_REGION_INFO.BANKNAME
     *
     * @mbg.generated Tue Mar 13 17:38:59 CST 2018
     */
    public void setBankname(String bankname) {
        this.bankname = bankname;
    }
}