package com.yinqiao.af.mapper;

import com.yinqiao.af.model.Announcement;
import java.util.List;

public interface AnnouncementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CYZG_KSXZ
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    int deleteByPrimaryKey(String msgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CYZG_KSXZ
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    int insert(Announcement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CYZG_KSXZ
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    Announcement selectByPrimaryKey(String msgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CYZG_KSXZ
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    List<Announcement> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CYZG_KSXZ
     *
     * @mbg.generated Sat Feb 03 13:41:51 CST 2018
     */
    int updateByPrimaryKey(Announcement record);
}