package com.yinqiao.af.mapper;

import com.yinqiao.af.model.Enroll;
import java.util.List;

public interface EnrollMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FJB_BMK
     *
     * @mbg.generated Tue Jan 30 15:07:06 CST 2018
     */
    int deleteByPrimaryKey(String bmkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FJB_BMK
     *
     * @mbg.generated Tue Jan 30 15:07:06 CST 2018
     */
    int insert(Enroll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FJB_BMK
     *
     * @mbg.generated Tue Jan 30 15:07:06 CST 2018
     */
    Enroll selectByPrimaryKey(String bmkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FJB_BMK
     *
     * @mbg.generated Tue Jan 30 15:07:06 CST 2018
     */
    List<Enroll> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FJB_BMK
     *
     * @mbg.generated Tue Jan 30 15:07:06 CST 2018
     */
    int updateByPrimaryKey(Enroll record);
    
    String queryIsEnrolled(String idcard);
}