package com.yinqiao.af.mapper;

import com.yinqiao.af.model.ExamList;

import java.util.List;

public interface ExamListMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AF_EXAM_LIST
	 * @mbg.generated  Tue Jan 09 09:57:58 CST 2018
	 */
	int deleteByPrimaryKey(String examId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AF_EXAM_LIST
	 * @mbg.generated  Tue Jan 09 09:57:58 CST 2018
	 */
	int insert(ExamList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AF_EXAM_LIST
	 * @mbg.generated  Tue Jan 09 09:57:58 CST 2018
	 */
	ExamList selectByPrimaryKey(String examId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AF_EXAM_LIST
	 * @mbg.generated  Tue Jan 09 09:57:58 CST 2018
	 */
	List<ExamList> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table AF_EXAM_LIST
	 * @mbg.generated  Tue Jan 09 09:57:58 CST 2018
	 */
	int updateByPrimaryKey(ExamList record);
}