package com.yinqiao.af.mapper;

import com.yinqiao.af.model.ExamHistory;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ExamHistoryMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AF_USER_EXAM_HISTORY
	 *
	 * @mbg.generated Thu Feb 08 10:50:40 CST 2018
	 */
	int deleteByPrimaryKey(String hId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AF_USER_EXAM_HISTORY
	 *
	 * @mbg.generated Thu Feb 08 10:50:40 CST 2018
	 */
	int insert(ExamHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AF_USER_EXAM_HISTORY
	 *
	 * @mbg.generated Thu Feb 08 10:50:40 CST 2018
	 */
	ExamHistory selectByPrimaryKey(String hId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AF_USER_EXAM_HISTORY
	 *
	 * @mbg.generated Thu Feb 08 10:50:40 CST 2018
	 */
	List<ExamHistory> selectAll(@Param("start") Integer start, @Param("end") Integer end,
			@Param("telnum") String telnum);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AF_USER_EXAM_HISTORY
	 *
	 * @mbg.generated Thu Feb 08 10:50:40 CST 2018
	 */
	int updateByPrimaryKey(ExamHistory record);

	String isExist(String hId);

	List<Map<String, Object>> studyTime(@Param("telnum") String telnum);

	int countByScore(@Param("telnum") String telnum, @Param("score") int score);
}