package com.yinqiao.af.mapper;

import com.yinqiao.af.model.OrderInfo;

import java.util.List;

public interface OrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AF_ORDER_INFO
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AF_ORDER_INFO
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    int insert(OrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AF_ORDER_INFO
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    OrderInfo selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AF_ORDER_INFO
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    List<OrderInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AF_ORDER_INFO
     *
     * @mbg.generated Mon Jan 29 11:58:37 CST 2018
     */
    int updateByPrimaryKey(OrderInfo record);
    
    String queryCntByProductId(String productId);
}