package com.yinqiao.af.mapper;

import com.yinqiao.af.model.Product;
import java.util.List;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AF_PRODUCT
     *
     * @mbg.generated Mon Jan 29 16:58:50 CST 2018
     */
    int deleteByPrimaryKey(String productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AF_PRODUCT
     *
     * @mbg.generated Mon Jan 29 16:58:50 CST 2018
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AF_PRODUCT
     *
     * @mbg.generated Mon Jan 29 16:58:50 CST 2018
     */
    Product selectByPrimaryKey(String productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AF_PRODUCT
     *
     * @mbg.generated Mon Jan 29 16:58:50 CST 2018
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AF_PRODUCT
     *
     * @mbg.generated Mon Jan 29 16:58:50 CST 2018
     */
    int updateByPrimaryKey(Product record);
}