package com.yinqiao.af.mapper;

import com.yinqiao.af.model.QuestionBank;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public interface QuestionBankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AF_QUESTION_BANK
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    int deleteByPrimaryKey(String questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AF_QUESTION_BANK
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    int insert(QuestionBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AF_QUESTION_BANK
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    QuestionBank selectByPrimaryKey(String questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AF_QUESTION_BANK
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    List<QuestionBank> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AF_QUESTION_BANK
     *
     * @mbg.generated Fri Jan 05 11:21:28 CST 2018
     */
    int updateByPrimaryKey(QuestionBank record);
    
    String isExist(String questionId);
    
	String getExamCount(String examId);
	
	List<Map> getQuestionCount(String examId);
	
	String getScore(List<String> rights);
	
	List<Map> queryTypeQuestionCount();
	
	QuestionBank queryTypeQuestion(HashMap<String, String> map);
	
    String isTypeExist(HashMap<String, String> map);
    
	String getTypeExamCount(HashMap<String, String> map);
	
	List<Map> getTypeQuestionCount(HashMap<String, String> map);
	
	String getOneTypeQuestionCount(String type);
}