package com.yinqiao.af.mapper;

import com.yinqiao.af.model.QuestionnaireModel;
import java.util.List;

public interface QuestionnaireModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WJ_TEST
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    int deleteByPrimaryKey(String testid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WJ_TEST
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    int insert(QuestionnaireModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WJ_TEST
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    QuestionnaireModel selectByPrimaryKey(String testid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WJ_TEST
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    List<QuestionnaireModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WJ_TEST
     *
     * @mbg.generated Thu May 24 10:36:24 CST 2018
     */
    int updateByPrimaryKey(QuestionnaireModel record);
}