package com.yinqiao.af.mapper;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.yinqiao.af.model.QuestionBank;

public interface QuestionBankMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AF_QUESTION_BANK
	 *
	 * @mbg.generated Fri Jan 05 11:21:28 CST 2018
	 */
	int deleteByPrimaryKey(String questionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AF_QUESTION_BANK
	 *
	 * @mbg.generated Fri Jan 05 11:21:28 CST 2018
	 */
	int insert(QuestionBank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AF_QUESTION_BANK
	 *
	 * @mbg.generated Fri Jan 05 11:21:28 CST 2018
	 */
	QuestionBank selectByPrimaryKey(String questionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AF_QUESTION_BANK
	 *
	 * @mbg.generated Fri Jan 05 11:21:28 CST 2018
	 */
	List<QuestionBank> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table AF_QUESTION_BANK
	 *
	 * @mbg.generated Fri Jan 05 11:21:28 CST 2018
	 */
	int updateByPrimaryKey(QuestionBank record);

	String isExist(String questionId);

	String getExamCount(String examId);

	List<Map> getQuestionCount(String examId);

	String getScore(List<String> rights);

	List<Map> queryTypeQuestionCount();

	String isTypeExist(HashMap<String, String> map);

	String getTypeExamCount(HashMap<String, String> map);

	List<Map> getTypeQuestionCount(HashMap<String, String> map);

	String getOneTypeQuestionCount(String type);

	List<QuestionBank> selectQuestions(@Param("start") int start, @Param("end") int end, @Param("examId") String examId,
			@Param("examType") String examType);

	int selectQuestionsCnt(@Param("examId") String examId, @Param("examType") String examType);
}