package com.yinqiao.af.mapper;

import com.yinqiao.af.model.User;
import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AF_USER
     *
     * @mbg.generated Wed Jan 24 15:20:54 CST 2018
     */
    int deleteByPrimaryKey(String telnum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AF_USER
     *
     * @mbg.generated Wed Jan 24 15:20:54 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AF_USER
     *
     * @mbg.generated Wed Jan 24 15:20:54 CST 2018
     */
    User selectByPrimaryKey(String telnum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AF_USER
     *
     * @mbg.generated Wed Jan 24 15:20:54 CST 2018
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AF_USER
     *
     * @mbg.generated Wed Jan 24 15:20:54 CST 2018
     */
    int updateByPrimaryKey(User record);
    
    String queryUserIsEffective(String idcard);
    
    String queryUserCnt(String telnum);

	List<User> selectByOpenid(String openid);
}